### ISSUE TITLE
Examples require external libraries

### ISSUE THREAD

**Issue by raysan5** [victorfisac/Physac#15]
When trying to execute example files (`.exe`), external DLL libraries are requested (MinGW libraries).

To avoid that, examples must be compiled using the following line:

*gcc -o $(NAME_PART).exe $(FILE_NAME) -s $(RAYLIB_DIR)\raylib\raylib_icon **-static** -lraylib **-lpthread** -lglfw3 -lopengl32 -lgdi32 -lopenal32 -lwinmm -std=c99 -Wl,--subsystem,windows -Wl,-allow-multiple-definition*

MinGW with GCC 5.3.0 should be used (includes updated pthread library).

**Comment by victorfisac** [comment]
Hi @raysan5 Thank you :D I have added it to the source and examples header. I removed the external DLL libraries from repo.

Commits: c3962a2, 6e4df11
