### ISSUE TITLE
cpu usage 100%

### ISSUE THREAD

**Issue by dzanis** [victorfisac/Physac#29]
The CPU overloaded,even if few bodies.What can I do? Thank you, for your work!  (Linux Mint x64)

**Comment by dzanis** [comment]
How to added manually update? For example  **void PhysicUpdate(double delta)**

**Comment by victorfisac** [comment]
Hi @dzanis. I cannot test the CPU overload in Linux platform...

By the other hand, to manually update physics you must calculate deltaTime by your own. To calculate it you need a timer counter to calculate increment of time.

I tried it and update physics calling PhysicsStep() in main thread but dynamics are not applied (even overwriting deltaTime value). But works colliders overlap solutions.
