### ISSUE TITLE
Physac naming and icon

### ISSUE THREAD

**Issue by raysan5** [victorfisac/Physac#33]
Hi @victorfisac, just noticed Physac icon only includes 16x16, 32x32 and 48x48 versions, directly scaled from the 256x256 .png version provided and physac_icon object does not include .rc properties correctly (just check generated .exe files to see that).

Do you mind if I review icon design following the proposed line but more aligned with [raylib iconography](https://github.com/raysan5/raylib/tree/develop/logo)?

**Comment by victorfisac** [comment]
Hi @raysan5 ! Yes, I had some problems trying to understand .rc properties and the icon generating pipeline for executables. Yes, I would be so glad if you review it. I will apply those improvements to other repos (FNode and rPBR).

**Comment by raysan5** [comment]
Implemented in PR https://github.com/victorfisac/Physac/pull/34
