### ISSUE TITLE
Where is PhysicsBody defined?

### ISSUE THREAD

**Issue by theamazingwaffle** [victorfisac/Physac#40]
You have this line:  
```c
typedef struct PhysicsBodyData *PhysicsBody;
```

But where is PhysicsBody defined?  
I am trying to do a rust port, should i just create a `struct PhysicsBody` or `struct PhysicsBodyData`?

**Comment by raysan5** [comment]
@theamazingwaffle actually that line is type-defining `(PhysicsBodyData *)` pointer as `PhysicsBody`, it means wherever you use `PhysicsBody` you're actually using `(PhysicsBodyData *)` pointer, that way the pointer format is seen directly.

**Comment by theamazingwaffle** [comment]
thanks
