### ISSUE TITLE
No shared libs (dlls, dylib, so) built for Physac

### ISSUE THREAD

**Issue by Rabios** [victorfisac/Physac#45]
Hi victor!
It is weird if i asked for shared library files for Physac,Cause i'm trying to bind it to LuaJIT

Is it okay if you offered built shared library files (dll, dylib, so) for Physac?
Sorry if i'm annoying you

And thanks for reading ^^

**Comment by raysan5** [comment]
@Rabios You should probably build it yourself...

**Comment by Rabios** [comment]
OK
