### ISSUE TITLE
Unresolved external symbol for QueryPerformanceCounter in Visual Studio 2019

### ISSUE THREAD

**Issue by RafaelOliveira** [victorfisac/Physac#50]
In VStudio 2019, QueryPerformanceCounter and QueryPerformanceFrequency needs theses headers to work:
#include <Windows.h>
#include <profileapi.h>
it's described here in the requirements section:
https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency

but if I include windows.h raylib and physac don't compile, because of function names conflict.

**Comment by Rabios** [comment]
@RafaelOliveira Looks like Victor does not work on this anymore, I will do this with my problem for my fork when i have time!

**Comment by Rabios** [comment]
@RafaelOliveira Done!
About function names conflict, Looks like it's this issue by mine which i also fixed it right now on my fork...

https://github.com/victorfisac/Physac/issues/49

Check my fork if you wanna: https://github.com/Rabios/Physac
