### ISSUE TITLE
Change return type of PhysicsLoop

### ISSUE THREAD

**Issue by EmperorPenguin18** [victorfisac/Physac#60]
When using the built-in pthreads functions, the return type of PhysicsLoop isn't used. However I'm trying to use SDL_CreateThread which expects the function to return an `int`. Could this be changed for better compatibility?

**Comment by victorfisac** [comment]
Feel free to open new pull requests with any change that makes this repository more compatible with your needs.
Thank you so much.

**Comment by victorfisac** [comment]
This change is not supported by pthreads.h
